[package]
name = "manufacter"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
reqwest = {version="0.12.9", features=["json"]}
serde_json = "1.0.133"
tokio = {version = "1.42.0", features = ["full"]}
