version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:8080"
    depends_on:
      - db
  db:
    build: ./db
    ports:
      - "6379:6379"
    volumes:
      - .data:/data
